# Generated by Django 2.1.7 on 2019-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
